### ISSUE TITLE
How to obtain .torrent links that are compatible with web torrent ? 

### ISSUE THREAD

**Issue by AlineGpp** [LostBeard/SpawnDev.BlazorJS.WebTorrents#1]
"Only found a link that works which is this one" : magnet:?xt=urn:btih:08ada5a7a6183aae1e09d831df6748d566095a10&dn=Sintel&tr=wss%3A%2F%2Ftracker.btorrent.xyz&tr=wss%3A%2F%2Ftracker.fastcast.nz&tr=wss%3A%2F%2Ftracker.openwebtorrent.com&ws=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2F&xs=https%3A%2F%2Fwebtorrent.io%2Ftorrents%2Fsintel.torrent 
How do I get more links in this format?

**Comment by LostBeard** [comment]
[Free Torrents](https://webtorrent.io/free-torrents)

A search engine is a good place to start. More information about magnet links can be found here [What Are Magnet Links, and How Do I Use Them to Download Torrents?](https://lifehacker.com/what-are-magnet-links-and-how-do-i-use-them-to-downloa-5875899) and here [Magnet URI scheme
](https://en.wikipedia.org/wiki/Magnet_URI_scheme)

The purpose of this project is to help developers integrate the torrent protocol into their applications.

This project and WebTorrent support both torrent files and magnet links.

Best of luck.
